### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by XavRsl** [mpociot/teamwork#19]
Hi,
The auth configuration file in Laravel 5.2 changed :
https://github.com/laravel/laravel/blob/develop/config/auth.php
So  `\Config::get( 'auth.table' )` in the migration file will no longer get the auth related table. 
Not sure how to get that table name with the new Laravel version...

Thanks,

Xavier

**Comment by mpociot** [comment]
Thanks. Fixed in version 2

**Comment by dennisoderwald** [comment]
Issue not fixed - `Config::get('auth.model')` there still exists in `TeamworkTeamTrait.php`
